# docker-compose.yml (Frontend service commented out for local development)
# Removed obsolete top-level 'version' key

services:
  # Backend API Service (FastAPI)
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
      - ./backend/tests:/app/app/tests
    env_file:
      - ./backend/.env
    container_name: modular_dashboard_api

  # Frontend Service (React + Nginx) - COMMENTED OUT FOR LOCAL DEV
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     # This would map host 5173 (or other) to container port 80 (Nginx) for production build serving
  #     - "5173:80"
  #   depends_on:
  #     - api
  #   container_name: modular_dashboard_frontend