# docker-compose.yml
# Orquestra os serviços do dashboard-adv e microsserviços integrados.

services:
  # API principal do dashboard-adv.
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: dashboard_adv_api # Alterado para dashboard-adv_api
    env_file:
      - ./backend/.env
    environment:
      - PYTHONPATH=/app
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  # Serviço de banco de dados compartilhado.
  db:
    # Imagem PostgreSQL com a extensão pgvector pré-instalada.
    image: pgvector/pgvector:pg16
    container_name: dashboard_adv_db # Alterado para dashboard-adv_db
    env_file:
      - ./backend/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-appuser} -d ${POSTGRES_DB:-appdb}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
