# Removed obsolete top-level 'version' key for cleaner V1 syntax
services:
  # Backend API Service (FastAPI)
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      # Mount the local backend app code into the container for development hot-reloading
      - ./backend/app:/app/app
      # Mount the local tests directory into the container
      - ./backend/tests:/app/app/tests
    env_file:
      - ./backend/.env
    container_name: modular_dashboard_api

  # Frontend Service (React + Nginx)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - api
    container_name: modular_dashboard_frontend